### ISSUE TITLE
Check if a Banner is currently showing

### ISSUE THREAD

**Issue by tochie-daniels** [sergivonavi/MaterialBanner#4]
How do you check if a banner is showing? That is so as not to show more than one banner at a time.

**Comment by ziadhassan7** [comment]
This library doesn't show up more than one banner at a time but we still need to check if the banner is currently shown or not.

**Comment by sergivonavi** [comment]
For historical purposes.

`Banner` inherits all `android.view.ViewGroup` methods. Therefore you can check if your banner is being displayed like that:
```
if (banner.isShown()) {
    // do something
}
```
