### ISSUE TITLE
I keep getting "InflateException" when i run my app

### ISSUE THREAD

**Issue by PabloPadilla5** [sergivonavi/MaterialBanner#5]
```
android.view.InflateException: Binary XML file line #24: Binary XML file #24: Error inflating class com.sergivonavi.materialbanner.Banner
```

**Comment by X1opya** [comment]
same problem on android 4.4

**Comment by X1opya** [comment]
fixed problem with creating banner programmaticaly. i think, it crashed cuz i use vector icons without `AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);` in Application class
